name = "seal"
description = "Seal CLI"
repository = "MystenLabs/seal"
main_branch = "main"
installation_type = "standalone"
network_based = false
supported_networks = []
default_network = "standalone"
supports_debug = false
cargo_package = "seal-cli"
nightly_toolchain = ""
shared_repo_binary = false
